### ISSUE TITLE
Dear Rivers,

### ISSUE THREAD

**Issue by emmettgb** [riverscuomo/riverscuomo.github.io#1]
Hey man, it's really cool to see you on here! I am a huge fan (I'll be sitting pit when you come to Atlanta this summer,) I wanted to fork this repository to see about potentially helping a little, but you keep deleting the repo to change the code.
You should try creating a new branch, it's on the top left of the repository, you can name it whatever. Typically features are implemented there and then pull requested at master. Each time you delete the repo, you delete your commits and the full history of commits, repository info, issues, wikis, etc. You can just upload modified files in place of old files.
I'm glad that you are practicing this skill and wearing this hat, more power to you man! Me (and my girlfriend) can't wait to see you in Atlanta! We have all your albums on vinyl!

**Comment by riverscuomo** [comment]
Thanks. I think I figured out how to push without starting over each time. I'd like the repo to be private (out of concern for my users' privacy), but it has to be public to publish on github pages. When I get a little further along I'll host it somewhere else that's private.

By the way, this Flutter app should eventually replace my Flask website: https://riverscuomo.com/chat . It's going to take a while.

**Comment by emmettgb** [comment]
If you're on a Unix-like system (mac or Linux), you can store all of your users data, sql keys, etc. In a .env file and load it into bash to be called with source .env. Then you can add it to the .gitignore file so it isn't committed when you push it, perhaps that could help with protecting your user's data. Github takes a bit of getting used to! Alternatively, you could make the repository private. You could always just use the old Flask app as a request template and just make requests to it to populate chat, etc. And have basically all the data for this be retrieved from endpoints.
Hope these suggestions are helpful, I have been doing this a while haha.
Also, if you are on Windows you could use something called WSL to get a real terminal, most people actually use Github through a terminal, not the website haha.

**Comment by tuf75588** [comment]
Hey Rivers! Netlify is a wonderful hosting provider that might suit your needs well down the line (I'm not affiliated with them in any way) you can link up your repositories with them and trigger new deployments on each push to your master branch.  Also +1 for WSL if you are Windows as @emmettgb mentioned. 

https://www.netlify.com/
